version: 1
formatters:
  brief:
    format: '%(levelname)s - %(message)s'
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: brief
loggers:
  pyfn:
    level: WARN
    handlers: [console]
  pyfn.unmarshallers:
    level: WARN
    handlers: [console]
root:
  level: WARN
  handlers: [console]
